error: change name and disable stack
@truffle/error's intent is to give the user an action to perform and
does not need a stack trace.

- rename @truffle/error to be TruffleError
- set the stack to  so there is not stacktrace when using bundle